# Generated by Django 5.0.1 on 2025-06-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_student_certificateexcelupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate_student',
            name='affiliated_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
