# Generated by Django 5.0.1 on 2025-06-29 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_student_affiliated_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='affiliated_name',
            field=models.CharField(default=0, help_text='Name of the Affiliated University', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='certificate',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='certificate_student',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='certificate_student',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
