# Generated by Django 5.2.3 on 2025-07-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificate_affiliated_name_certificate_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(editable=False, help_text='Unique identifier for the certificate', max_length=18, unique=True),
        ),
    ]
